### ISSUE TITLE
curl_noise_4D.tox output pixel format not matching custom parameter menu

### ISSUE THREAD

**Issue by brvoigt** [DBraun/TouchDesigner_Shared#1]
Thanks for this great Noise COMP. Since you are using index into the Pixel Format menu of glslmulti1, in the latest 099 build I am using this is not giving the correct result. The index will change whenever Derivative adds new entries to the menu, so its not the most reliable method. To be sure of it you can use a Table DAT to export the string token for the menu entry, something which will be consistent (mostly) when Derivative adds more the the menu. I have attached a simple example of how to do that, but it still needs to be hooked up to your custom parameter menu so it switches.

Also for consideration, maybe 16-bit float is best default because 32-bit floats really hit performance hard and when people start appending extra TOP filters after this COMP they may not notice or realize that the pixel format is the reason their performance is getting killed. 

[curl_noise_4D_TableExport.zip](https://github.com/DBraun/TouchDesigner_Shared/files/791300/curl_noise_4D_TableExport.zip)

![formatoffset](https://cloud.githubusercontent.com/assets/8110813/23181851/8f066ec2-f844-11e6-82a4-4aa9fa43de13.png)

**Comment by DBraun** [comment]
Thanks I'll take a look soon.

**Comment by DBraun** [comment]
Check out the latest file when you've got a chance. I'll be on the lookout for fixing this pixel format issue elsewhere.

**Comment by brvoigt** [comment]
Yeah that fixed it, great!
