### ISSUE TITLE
GLSL similar errors in 2 examples

### ISSUE THREAD

**Issue by brvoigt** [DBraun/TouchDesigner_Shared#2]
There are similar errors in kohonen.tox and kuwahara.tox, the shader complaing about using "sample" after a type declaration. Using 099 on Windows 10 and Nvidia GPU

[kohonen.txt](https://github.com/DBraun/TouchDesigner_Shared/files/791363/kohonen.txt)
[kuwahara.txt](https://github.com/DBraun/TouchDesigner_Shared/files/791362/kuwahara.txt)

**Comment by DBraun** [comment]
Thanks for catching that. I made those files with 088. 099's GLSL compiler probably doesn't allow "sample" as a variable name. Let me know if the most recently pushed files work for you.

**Comment by brvoigt** [comment]
Kuwahara is working but an error in kohonen which looks like a typo (.za?)
[info1.txt](https://github.com/DBraun/TouchDesigner_Shared/files/801518/info1.txt)

**Comment by DBraun** [comment]
That line works for me. Does .zw work?

**Comment by brvoigt** [comment]
Sorry I missed your reply! In Kohonen it is now working in Windows but on macOS still gives the same error. When I replace .za with .zw it compiles successfully.

I found if I click reset on the parent parameters (with default settings supplied) it hangs the GPU, both on mac and windows. Hard reboot required. Have any tips to try?

**Comment by brvoigt** [comment]
Yeah that was it, I didn't realize that was a limitation.
