### ISSUE TITLE
Optical Flow issue

### ISSUE THREAD

**Issue by lturczan** [DBraun/TouchDesigner_Shared#3]
Thanks for porting PixelFlow into TouchDesigner - seems like an incredibly useful tool.

I'm getting a pixel shader compiling error in the sobel glsl, it says: 
ERROR: 0:9: '{' : syntax error: syntax error

Thanks!

[OpticalFlow.1.toe.zip](https://github.com/DBraun/TouchDesigner_Shared/files/2573270/OpticalFlow.1.toe.zip)

**Comment by DBraun** [comment]
Closing issue. Please re-open if there's still an issue.
