### ISSUE TITLE
Bug in TD-Boids get_bins component?

### ISSUE THREAD

**Issue by mickeyvanolst** [DBraun/TouchDesigner_Shared#7]
![image](https://github.com/DBraun/TouchDesigner_Shared/assets/1071097/23a10a2c-df44-4de8-bf31-2042d15dfa5f)

Hi David

I'm having a go at porting your voxelized lookup feature to another simulation. Basically just some regular particles in a compute shader  that can collide with each other. And I noticed something strange in the get_bins component.

As you can see in the screenshot, there is a voxel that claims to be overflown with particles (in the texture its the lower left pixel), yet in the texture holding the positions, there is not a single particle in that voxel area. I'm bounding the positions to be slightly inside the bounds of the voxel world measurements. The issue doesn't happen immediately, but builds up over the course of the first 30 seconds or so. 

Do you think this could be a bug of the bin counting shader?

**Comment by DBraun** [comment]
For your new project, I wonder if there's an incorrect export on the parameters of `geo_debug_occupancy/glslmulti1`. I probably shouldn't have used a Parameter CHOP inside that base. By the way, `binFullPct`==1 would indicate that the most occupied bin is maximally full.

**Comment by mickeyvanolst** [comment]
![image](https://github.com/DBraun/TouchDesigner_Shared/assets/1071097/8a33eb52-35b2-4a0a-a6b3-8898f69837f6)

I don't think that's the case sadly. I'm not using the parameter CHOP. Instead I am directly referencing the parameters on get_bins.

**Comment by DBraun** [comment]
Do you think you could share the tox or a simplified version?
* Use a small particle count while still reproducing the issue.
* Freeze any TOPs that are relevant. I will unfreeze them.

**Comment by mickeyvanolst** [comment]
Hi @DBraun 

Sorry I missed seeing the notification of your reply somehow.

[computeCollisionSetup.zip](https://github.com/DBraun/TouchDesigner_Shared/files/14237593/computeCollisionSetup.zip)

Luckily the example is already quite simplified, I made it as a test to later integrate into something bigger.

**Comment by DBraun** [comment]
Cool example. It looks like you have NaN's due to the compute shader.

I replaced `normalize` with
```glsl
vec3 normx(vec3 x) {
    return x == vec3(0) ? x : normalize(x);
}
```
and then it works as expected.

**Comment by mickeyvanolst** [comment]
oh wow, great find! Sorry to keep you busy, I completely overlooked that. 

Amazing work on the flocking example, I really enjoyed dissecting things a bit. I'm planning to use the binning algorithm to add collisions in https://github.com/mickeyvanolst/TD-chainGpu-Physics-Sim-Tool

Have you seen the hash based binning algorithm that Sebastian Lague implemented btw? https://github.com/SebLague/Fluid-Sim
Rather than allocating part of the texture per bin, it allows you to use the entire texture independent of how the bins are subdivided. Might be something to consider in the future, Josef Pelz made in implementation of it in TD that looked very promising.

Anyhow, thanks again!
